name: Just workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        
        steps:

        - name: Checkout
          uses: actions/checkout@v6

        - name: Welcome message
          run: echo "Fist GitHubActions Job"

        - name: List fFiles
          run: ls

        - name: Read File
          run: cat README.md
          
