name: Generate ASCII Artwork

on:
    push

jobs:
    acsii-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: List Repo Files
          run: ls -ltra

        - name: Executing Shell script
          run: |
            chmod +x ascii-script.sh
            ./.github/workflows/ascii-script.sh
